name: Docker Image Build Test

on:   
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.gitignore'
      - 'docs/**'

env:
  IMAGE_NAME_Scanner: jellyfin-intro-scanner-test
  IMAGE_NAME_Skipper: jellyfin-intro-skipper-test
  #VERSION: 0.0.2

jobs:
  Scanner_Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f Dockerfile_Jellyfin-Intro-Scanner -t jellyfin-intro-scanner-test .
          
  Skipper_Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f Dockerfile_Jellyfin-Intro-Skipper -t jellyfin-intro-skipper-test .
