name: Docker Test Build Jellyfin Intro Scanner

on:   
  pull_request:
    paths:
      - '**.py'
      - 'Dockerfile_Jellyfin-Intro-Scanner'
      - '!jellyfin_auto_skip.py'
      - '!diff_jellyfin_cache.py'
      - '!Dockerfile_Jellyfin-Intro-Skipper'
      - '!**.md'
      - '!**.gitignore'
      - '!docs/**'
      - '!.github/**'

env:
  IMAGE_NAME_Scanner: jellyfin-intro-scanner-test

jobs:
  Test_Build_Scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -f Dockerfile_Jellyfin-Intro-Scanner -t jellyfin-intro-scanner-test .